site_name: NoahHsu's Server Side Journal
site_url: https://noahhsu.github.io/
repo_url: https://github.com/NoahHsu/noahhsu.github.io
edit_uri: 'edit/main/docs/'

site_author: NoahHsu

theme:
  name: cyborg
  custom_dir: custom_theme/
  hljs_languages:
    - yaml
    - java
