site_name: NoahHsu's Life Note
site_url: https://noahhsu.github.io/
repo_url: https://github.com/NoahHsu/noahhsu.github.io
edit_uri: 'edit/main/docs/'

site_author: NoahHsu
copyright: © 2023-"current year.",  Noah Hsu, All Rights Reserved

theme:
  name: material
  custom_dir: custom_theme/
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: brown
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: blue grey
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.top
    - navigation.expand
    - search.suggest
    - search.highlight
    - header.autohide
    - content.code.copy
    - content.code.select
    - content.code.annotate
  hljs_languages:
    - yaml
    - java
    - javascript

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/NoahHsu
    - icon: simple/buymeacoffee
      link: https://www.buymeacoffee.com/swbhcjhtyvv
    - icon: fontawesome/brands/medium
      link: https://medium.com/@noahhsu
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/tzu-ting-hsu-72a32715a/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/noahorsehsu
  analytics:
    provider: google
    property: G-J8TC3WPHWC
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/thumb-up-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/thumb-down-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            <a href="https://github.com/NoahHsu/noahhsu.github.io/issues/new" target="_blank" rel="noopener">create issue</a> in my GitHub Repo.
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

plugins:
  - blog:
      blog_dir: Software Engineering Blog
      blog_toc: true
      archive_name: History-Post
      archive_date_format: yyyy
      categories_allowed:
        - Developer Experience
        - DevOps
        - Spring Boot
        - System Design
        - Coding
      authors_profiles: true
      pagination_per_page: 5
  - tags:
      tags_file: Software Engineering Blog/tags.md
  - search:
      min_search_length: 2
      separator: '[\s\-\.]+'
  - glightbox
  - encryptcontent:
      password_file: 'passwords.yml'


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html
  - abbr
  - toc:
      permalink: true


extra_css:
  - stylesheets/chords.css
extra_javascript:
  - javascripts/lyrics-convertor.js
  - javascripts/autoscroll.js

