site_name: Noah's Tech Ark
site_url: https://noahhsu.github.io/
repo_url: https://github.com/NoahHsu/noahhsu.github.io
edit_uri: 'edit/main/docs/'

site_author: NoahHsu

extra_javascript:
  - path: analytics.js

theme:
  name: journal
  hljs_languages:
    - yaml
    - java
