site_name: NoahHsu's SWE Note
site_url: https://noahhsu.github.io/
repo_url: https://github.com/NoahHsu/noahhsu.github.io
edit_uri: 'edit/main/docs/'

site_author: NoahHsu

theme:
  name: spacelab
  custom_dir: custom_theme/
  hljs_languages:
    - yaml
    - java

plugins:
  - search:
      min_search_length: 2
      separator: '[\s\-\.]+'