site_name: NoahHsu's Software Engineer Ark
site_url: https://noahhsu.github.io/
repo_url: https://github.com/NoahHsu/noahhsu.github.io

site_author: NoahHsu

theme:
  name: journal
  hljs_languages:
    - yaml
    - java

