site_name: Noah's Tech Ark
site_url: https://noahhsu.github.io/
repo_url: https://github.com/NoahHsu/noahhsu.github.io
edit_uri: 'edit/main/docs/'

site_author: NoahHsu
google_analytics: ['G-J8TC3WPHWC', 'https://noahhsu.github.io']

theme:
  name: journal
  hljs_languages:
    - yaml
    - java
