name: Publish
on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - '.github/workflows/publish.yaml'
      - mkdocs.yml

  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: false

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN}}
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install Python dependencies
        run: |
          pip install \
            "mkdocs" \
            "mkdocs-material" \
            "mkdocs-bootswatch" \
            "mkdocs-git-revision-date-plugin" \
            "mkdocs-glightbox" \
            "mkdocs-encryptcontent-plugin"

#      - name: Unlock secrets
#        uses: sliteteam/github-action-git-crypt-unlock@1.2.0
#        env:
#          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}

      - name: Install git-crypt
        run: |
          sudo apt-get update
          sudo apt-get install -y git-crypt

      - name: Unlock git-crypt
        run: |
          git-crypt init
          echo ${{ secrets.GIT_CRYPT_KEY }} | base64  -d > ./git-crypt-key
          git-crypt unlock ./git-crypt-key
          rm ./git-crypt-key

      - name: check git-crypt status
        run: |
          git-crypt status

      - name: Build Site
        run: mkdocs build

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './site/'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
